# Generated by Django 4.2.6 on 2023-10-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imgrecord',
            options={'verbose_name': 'File for training', 'verbose_name_plural': 'Files for training'},
        ),
        migrations.AddField(
            model_name='imgrecord',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
