# Generated by Django 4.2.6 on 2023-10-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_imgrecord_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgrecord',
            name='unrecognizable',
            field=models.BooleanField(default=False, verbose_name='Unrecognizable'),
        ),
        migrations.AlterField(
            model_name='imgrecord',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='Мerified by a human'),
        ),
        migrations.AlterField(
            model_name='imgrecord',
            name='file_name',
            field=models.CharField(max_length=30, unique=True, verbose_name='File name'),
        ),
    ]
