# Generated by Django 4.2.6 on 2023-10-18 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_imgrecord_unrecognizable_alter_imgrecord_checked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='imgrecord',
            name='file_name',
        ),
        migrations.AddField(
            model_name='imgrecord',
            name='user_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='training.userimg', verbose_name='Parent picture'),
        ),
    ]
