# Generated by Django 4.2.6 on 2023-10-18 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_userimg_remove_imgrecord_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgrecord',
            name='user_img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.userimg', verbose_name='Parent picture'),
        ),
    ]
