# Generated by Django 4.2.6 on 2023-10-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_alter_imgrecord_user_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userimg',
            options={'verbose_name': 'Uploaded image', 'verbose_name_plural': 'Uploaded images'},
        ),
        migrations.AddField(
            model_name='imgrecord',
            name='user_content',
            field=models.CharField(blank=True, max_length=30, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='imgrecord',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='Verified by a human'),
        ),
    ]
