# Generated by Django 4.2.6 on 2023-10-21 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_alter_userimg_options_imgrecord_user_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmallImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_pic', models.CharField(blank=True, max_length=50, verbose_name='Parent pic name')),
                ('image_file', models.ImageField(blank=True, upload_to='images/')),
                ('quality', models.DecimalField(decimal_places=5, max_digits=7)),
                ('content', models.CharField(blank=True, max_length=30, verbose_name='AI recognition')),
                ('user_content', models.CharField(blank=True, max_length=30, verbose_name='Human recognition')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('unrecognizable', models.BooleanField(default=False, verbose_name='Unrecognizable')),
                ('checked', models.BooleanField(default=False, verbose_name='Verified by a human')),
            ],
            options={
                'verbose_name': 'Pic for training',
                'verbose_name_plural': 'Pics for training',
            },
        ),
        migrations.AlterField(
            model_name='imgrecord',
            name='content',
            field=models.CharField(blank=True, max_length=30, verbose_name='AI recognition'),
        ),
        migrations.AlterField(
            model_name='imgrecord',
            name='user_content',
            field=models.CharField(blank=True, max_length=30, verbose_name='Human recognition'),
        ),
    ]
